version: '2'

services:
 postgres:
  container_name: my_postgres
  image: postgres
  ports:
   - "5432:5432"
  environment:
   - POSTGRES_USER=postgres
   - POSTGRES_PASSWORD=postgres
  volumes:
   - ./postgres-data:/var/lib/postgresql/data
